alias bbu='byobu'
alias cl='clear && ls'
alias clr='clear'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gpu13='ssh gpu013'
alias gpu14='ssh gpu014'
alias grep='grep --color=auto'
alias grun='java -Xmx500M -cp "/lfs/usrhome/oth/cs20mtech01004/ret-sum-modified/antlr-4.9-complete.jar:$CLASSPATH" org.antlr.v4.gui.TestRig'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias nw='watch --interval=1 nvidia-smi'
alias qn='watch --interval=1 "qstat -u cs20mtech01004 -n1 && echo $"\n" && nvidia-smi"'
alias qs='qstat -u cs20mtech01004'
alias qstat='qstat -anu cs20mtech01004'
alias quota='/lfs/home/quotaforusers'
alias qw='watch --interval=1 qstat -u cs20mtech01004 -n1'
alias std='f(){ tail -f -n +1 "$@" ;  unset -f f; }; f'
alias std1='f(){ tail -f -n +1 /proc/"$@"/fd/1 ;  unset -f f; }; f'
alias std2='f(){ tail -f -n +1 /proc/"$@"/fd/2 ;  unset -f f; }; f'
alias vi='vim'
alias create='f(){ conda env create -f "$@" ;  unset -f f; }; f'
